### ISSUE TITLE
没有数据显示

### ISSUE THREAD

**Issue by Michael-py001** [lixianmin/git.stats#3]
![image](https://github.com/user-attachments/assets/20bedaeb-37f1-44f3-885d-56227fa0abd0)
每个项目打开都不显示，应该是有bug

**Comment by lixianmin** [comment]
应该是您的项目最后一次提交的时间远在今天之前, 所以这个区间里没有数据. 我想一下应该怎么应对这种情况

感谢指正

**Comment by lixianmin** [comment]
问题已经修正, 请更新

感谢指正
