### ISSUE TITLE
显示区域重叠

### ISSUE THREAD

**Issue by ilikerome** [lixianmin/git.stats#6]
![image](https://github.com/user-attachments/assets/3bc9ec2b-a64d-482e-bb9e-29f5a45dcc99)

**Comment by lixianmin** [comment]
那个圆的饼图， 是可以拖走的。 鼠标左键按住，拖一下

**Comment by lixianmin** [comment]
并没有故意设计成永远不能重叠哈，因为有可能咱们的代码量很大，永远找不到不会重叠的地方

**Comment by ilikerome** [comment]
> 并没有故意设计成永远不能重叠哈，因为有可能咱们的代码量很大，永远找不到不会重叠的地方

明白了，tks
